name: flutter_github_scripts
description: Scripts to provide reports on Flutter's code health.
publish_to: none
version: 0.0.1
author: Ray Rischpater, KF6GPE <rischpater@google.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  csv:  ^4.0.0
  quiver: '>=2.0.0 < 3.0.0'
  glob: ^1.0.3
  path:
  lcov:
  intl:
  graphql: ^2.0.0
  columnar_output:
    git: https://github.com/kf6gpe/columnar-output.dart.git

dev_dependencies:
  test: ^1.0.0
  pedantic:
