name: flutter_github_scripts
description: Scripts to provide reports on Flutter's code health.
publish_to: none
version: 0.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.2.0
  csv:  ^5.0.0
  glob: ^2.0.1
  graphql: ^5.0.0
  intl: ^0.17.0
  lcov: ^6.0.0
  path: ^1.8.0
  quiver: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.12
