name: flutter_github_scripts
description: Scripts to provide reports on Flutter's code health.
publish_to: none
version: 0.0.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^2.2.0
  columnar_output:
    git: https://github.com/csells/columnar-output.dart.git
  csv:  ^5.0.0
  glob: ^2.0.1
  graphql: ^5.0.0
  intl: any
  lcov: any
  path: any
  quiver: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.12
