name: flutter_github_scripts
description: Scripts to provide reports on Flutter's code health.
publish_to: none
version: 0.0.1
author: Ray Rischpater, KF6GPE <rischpater@google.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^2.1.0
  csv: ^5.0.0
  quiver: ^3.0.1
  glob: ^2.0.1
  path: ^1.8.0
  intl: ^0.17.0
  graphql: ^5.0.0-nullsafety.4
  columnar_output:
    git: https://github.com/eseidel/columnar-output.dart.git

dev_dependencies:
  test: ^1.17.3
  pedantic: ^1.11.0
